spring.application.name=poke-api
spring.graphql.graphiql.enabled=true
spring.graphql.cors.allowed-origins=http://localhost:3000
spring.graphql.cors.allowed-methods=POST,OPTIONS
spring.graphql.cors.allowed-headers=*